<%@ WebService Language="C#" CodeBehind="SMLIBFWW_LISTBUILDER_S.asmx.cs" Class="SMLIBFWW_WIDGET_LISTBUILDER.SMLIB_Web_JS.SMLIBFWW_WIDGET.SMLIB_FW_WIDGET_LISTBUILDER.SERVICE.SMLIBFWW_LISTBUILDER_S" %>
