
IF NOT 'LISTBUILDER' in (SELECT SMLIB_WIDGET_GROUP.WIDGET_NAME FROM SMLIB_WIDGET_GROUP)
INSERT INTO SMLIB_WIDGET_GROUP 
(
  WIDGET_NAME,
  WIDGET_DISPLAY_NAME,
  WIDGET_DESCRIPTION,
  WIDGET_PACKAGE,
  WIDGET_VERSION,
  WIDGET_CREATOR,
  WIDGET_CREATION_DATE,
  WIDGET_INSTALL_DATE,
  WIDGET_INSTALLER,
  WIDGET_UPDATE_DATE,
  WIDGET_UPDATER,
  WIDGET_DEFAULT_FUNCTION,
  WIDGET_GROUP_CONFIGURABLE,
  WIDGET_GROUP_REMOVEABLE
) 
VALUES
(
  'LISTBUILDER',
  'Smart List Builder',
  'Smart List Builder Widget',
  'Smart Suite Widget',
  '1.0.0',
  'FUNCTIONAL SOLUTIONS',
  CONVERT(datetime,'01/08/2017 00:00:00',103),
  getdate(),
  '[INSTALLER]',
  getdate(),
  '[INSTALLER]',
  'VIEWER',
  1,
  1
)
/*SQLCOMMAND*/
IF NOT 'LISTBUILDER' in (SELECT SMLIB_WIDGET_GROUP_CATEGORY.WIDGET_NAME FROM SMLIB_WIDGET_GROUP_CATEGORY)
INSERT INTO SMLIB_WIDGET_GROUP_CATEGORY (WIDGET_GROUP_ID,WIDGET_NAME,WIDGET_VERSION,WIDGET_CATEGORY) 
SELECT TOP 1 SMLIB_WIDGET_GROUP.WIDGET_GROUP_ID, SMLIB_WIDGET_GROUP.WIDGET_NAME, SMLIB_WIDGET_GROUP.WIDGET_VERSION, 'SEARCH' as WIDGET_CATEGORY  FROM SMLIB_WIDGET_GROUP WHERE WIDGET_NAME='LISTBUILDER'
/*SQLCOMMAND*/

IF NOT 'SMLIBFWW_LISTBUILDER_W_CREATE' in (SELECT SMLIB_WIDGET.WIDGET_ELEMENT FROM SMLIB_WIDGET)
INSERT INTO SMLIB_WIDGET
(
  WIDGET_GROUP_ID,
  WIDGET_ELEMENT,
  WIDGET_ELEMENT_DISPLAY,
  WIDGET_DESCRIPTION,
  WIDGET_PLUGIN_ABLE,
  WIDGET_ITEM_CONFIGURABLE
 ) 
VALUES
(
  (SELECT TOP 1 SMLIB_WIDGET_GROUP.WIDGET_GROUP_ID FROM SMLIB_WIDGET_GROUP WHERE SMLIB_WIDGET_GROUP.WIDGET_NAME='LISTBUILDER'),
  'SMLIBFWW_LISTBUILDER_W_CREATE',
  'Smart List Builder Create',
  'Smart List Builder Create Widget',
  1,
  1
)
/*SQLCOMMAND*/

DECLARE @RC int

EXECUTE @RC = [dbo].[SMLIB_FullResetWidgetFunction] 

/*SQLCOMMAND*/

/*END*/